### ISSUE TITLE
Async/Await Does not wait

### ISSUE THREAD

**Issue by jcm10x1** [HelloFro/yelp_fusion_client#1]
Calling fetchBusinessSearch with await does not wait for results, returning 0.

**Comment by HelloFro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Async/Await does not wait](https://trello.com/c/Q8OfM0Mp/2-async-await-does-not-wait)

**Comment by HelloFro** [comment]
@jcm10 Lat+Long are _required_ **OR** Location is _required_. 
Use a catch: 
```dart
fetchBusinessSearch(params).then(processReturnedZero).catchError(AssertionError e);
``` 
#5
