### ISSUE TITLE
fetchBusinessSearch image_url always returned Null when asObject is True. Returns correctly when false

### ISSUE THREAD

**Issue by McCossum** [HelloFro/yelp_fusion_client#10]
Using fetchBusinessSearch the image_url field is always null when running is object. Switching it over to JSON returns the expected parameters.

**Comment by HelloFro** [comment]
Hello @McCossum,
I ran a few tests covering this bug, but was unable to recreate.
Can you provide me with more detailed information about the parameters you were using when calling `fetchBusinessSearch`?
Screenshots of the error or the exact parameters should help with triaging this issue.

**Comment by Adam-D-Lewis** [comment]
Here's a reproducible example showing this bug.
![image](https://user-images.githubusercontent.com/23342526/176591214-5a4651f2-4e00-425b-b67f-07ee0d586671.png)
![image](https://user-images.githubusercontent.com/23342526/176591369-6ad75eb6-bce9-4413-86f6-5c2e7f047d16.png)

**Comment by HelloFro** [comment]
> Here's a reproducible example showing this bug. ![image](https://user-images.githubusercontent.com/23342526/176591214-5a4651f2-4e00-425b-b67f-07ee0d586671.png) ![image](https://user-images.githubusercontent.com/23342526/176591369-6ad75eb6-bce9-4413-86f6-5c2e7f047d16.png)

Thanks for providing these screenshots! @Adam-D-Lewis 

I believe I have figured out what is causing the bug and will hotfix it shortly.

cc @McCossum
