### ISSUE TITLE
fetchBusinessSearch returns max 50 results

### ISSUE THREAD

**Issue by Adam-D-Lewis** [HelloFro/yelp_fusion_client#11]
Docs on https://pub.dev/packages/yelp_fusion_client/versions/0.2.0+3 say `fetchBusinessSearch() : Get up to 1000 businesses based on the provided search criteria`, but setting limit parameter > 50 throws an error.

**Comment by HelloFro** [comment]
> **How do I get more than 50 results per request and how to get more than 1000 businesses?**
The API can only return up to 1,000 results at this time. The API doesn't allow more than 50 per request. You need to use the offset parameter to get the next page of results. (For using offset, give it any number. If you have limit=50, that means you're getting results 1-50, so give it offset=51 and you'll get 51-100.)

[Yelp Fusion - FAQ](https://www.yelp.com/developers/faq)
