### ISSUE TITLE
No Null Safety Support

### ISSUE THREAD

**Issue by jcm10x1** [HelloFro/yelp_fusion_client#2]

**Comment by jcm10x1** [comment]
I have lots of errors and this is hard to work with without null safety support.

**Comment by HelloFro** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Migration to Null Safety](https://trello.com/c/B7pEqlEH/1-migration-to-null-safety)

**Comment by HelloFro** [comment]
#3
